package entity;

public enum OrderStates {
    READY_TO_SEND,
    ON_THE_WAY_TO_THE_WAREHOUSE,
    ON_THE_WAREHOUSE,
    ON_THE_WAY_TO_THE_FINAL_WAREHOUSE,
    ON_THE_FINAL_WAREHOUSE,
    ON_THE_WAY_TO_THE_RECEPTION,
    ORDER_COMPLETED,
    ORDER_LOCKED
}
